# git-statistics Project Settings

github_user: leonardokr

# Available themes:
#   GitHub: default, light, dark, github_dimmed
#   Popular: dracula, nord, gruvbox, gruvbox_light, one_dark, monokai, tokyo_night, solarized_dark, solarized_light
#   Catppuccin: catppuccin_latte, catppuccin_frappe, catppuccin_macchiato, catppuccin_mocha
#   Material: palenight, material_darker, material_ocean, ayu, ayu_light, ayu_mirage
#   Creative: synthwave, cyberpunk, ocean, forest, sunset, midnight, aurora, neon, retro, lavender, rose_pine, rose_pine_dawn
#   Use 'all' to generate images for all available themes
themes:
  enabled:
    - light
    - dark

timezone: America/Sao_Paulo

commit_user_name: GitHub Action
commit_user_email: action@github.com

stats_generation:
  excluded_repos: ""
  excluded_langs: ""
  include_forked_repos: "false"
  exclude_contrib_repos: "false"  # Exclude repos where you are only a contributor
  exclude_archive_repos: "true"
  exclude_private_repos: "false"
  exclude_public_repos: "false"
  store_repo_views: "true"   # Accumulate views count over time
  store_repo_clones: "true"  # Accumulate clones count over time
  more_collabs: 0            # Manually add extra collaborators count
  manually_added_repos: ""   # Format: owner/repo,owner/repo
  only_included_repos: ""    # If set, only these repos are included

  # Set to "false" to hide specific stats
  show_total_contributions: "true"
  show_repositories: "true"
  show_lines_changed: "true"
  show_avg_percent: "true"
  show_collaborators: "true"
  show_contributors: "true"
  show_views: "true"
  show_clones: "true"
  show_forks: "true"
  show_stars: "true"
  show_pull_requests: "true"
  show_issues: "true"
